[package]
name = "storm_client"
version = "0.1.0"
authors = ["Mackenzie Clark <mackenzie.a.z.c@gmail.com>"]

[dependencies]
conrod = "0.61.1"
find_folder = "0.3.0"
rand = "0.5.5"

[features]
winit = ["conrod/winit"]
piston = ["conrod/piston"]
glium = ["conrod/glium"]