version: 2
jobs:
  get_project:
    working_directory: ~/project/storm
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - persist_to_workspace:
          root: "."
          paths:
            - client
            - server
  build_client:
    working_directory: ~/project/storm
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/storm
      - run:
          name: Build Client
          command: cargo build --manifest-path=client/Cargo.toml
      - persist_to_workspace:
          root: client
          paths:
            - target
      - save_cache:
          key: client-app-cache
          paths:
          - "~/.cargo"
      - run:
          name: ls
          command: ls
  test_client:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/storm
      - restore_cache:
          key: client-app-cache
      - run:
          name: Test Client
          command: cargo test --manifest-path=client/Cargo.toml
  build_server:
    working_directory: ~/project/storm
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: Build Server
          command: cargo build --manifest-path=server/Cargo.toml
      - persist_to_workspace:
          root: server
          paths:
            - target
      - save_cache:
          key: server-cache
          paths:
          - "~/.cargo"
  test_server:
    docker:
    - image: circleci/rust
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/storm
      - restore_cache:
          key: server-cache
      - run:
          name: Test Server
          command: cargo test --manifest-path=server/Cargo.toml
workflows:
  version: 2
  build:
    jobs:
      - get_project
      - build_client:
          requires:
            - get_project
      - test_client:
          requires:
            - build_client
      - build_server:
          requires:
            - get_project
      - test_server:
          requires:
            - build_server
#    - deploy:
#        requires:
#        - build
#        filters:
#          branches:
#only: master
