version: 2

jobs:
  get_project:
    working_directory: /tmp
    docker:
    - image: circleci/rust
    steps:
    - checkout
    - persist_to_workspace:
        root: "./client/"
        paths:
        - client
        - server
  build_client:
    working_directory: /tmp/client
    docker:
    - image: circleci/rust
    steps:
    - checkout
    - restore_cache:
        key: client-app-cache
    - run:
        name: Build Client
        command: cargo build
    - persist_to_workspace:
        root: "./client/"
        paths:
          - target
          - save_cache:
              key: client-app-cache
              paths:
              - "~/.cargo"
              - "./target"
  test_client:
    working_directory: /tmp/client
    docker:
    - image: circleci/rust
    steps:
    - checkout
    - restore_cache:
        key: client-app-cache
    - run:
        name: Test Client
        command: cargo test
  build_server:
    working_directory: /tmp/client
    docker:
    - image: circleci/rust
    steps:
    - checkout
    - restore_cache:
        key: server-cache
    - run:
        name: Build Server
        command: cargo build
    - persist_to_workspace:
        root: "./server/"
        paths:
        - target
        - save_cache:
            key: server-cache
            paths:
            - "~/.cargo"
            - "./target"
  test_server:
    working_directory: /tmp/server
    docker:
    - image: circleci/rust
    steps:
    - checkout
    - restore_cache:
        key: server-cache
    - run:
        name: Test Server
        command: cargo test
workflows:
  version: 2
  build:
    jobs:
    - build_client
        requires:
        - get_project
    - build_server
      requires:
        - get_project
#    - deploy:
#        requires:
#        - build
#        filters:
#          branches:
#only: master
