version: 2
jobs:
  test_client:
    working_directory: ~/project/storm
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - restore_cache:
          keys:
          - client-app-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "client/Cargo.toml" }}
          - client-app-cache-v1-{{ arch }}-{{ .Branch }}
          - client-app-cache-v1-
      - run:
          name: Test Client
          command: cargo test --manifest-path=client/Cargo.toml
      - save_cache:
          key: client-app-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "client/Cargo.toml" }}
          paths:
          - "~/.cargo"
          - "~/project/storm/client/target"
  test_server:
    working_directory: ~/project/storm
    docker:
    - image: circleci/rust
    steps:
      - checkout
      - restore_cache:
          keys:
          - server-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "server/Cargo.toml" }}
          - server-cache-v1-{{ arch }}-{{ .Branch }}
          - server-cache-v1-
      - run:
          name: Test Server
          command: cargo test --manifest-path=server/Cargo.toml
      - save_cache:
          key: server-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "server/Cargo.toml" }}
          paths:
          - "~/.cargo"
          - "~/project/storm/server/target"
workflows:
  version: 2
  build:
    jobs:
      - test_client
      - test_server
#    - deploy:
#        requires:
#        - build
#        filters:
#          branches:
#only: master
