[package]
name = "storm_server"
version = "0.1.0"
authors = ["Danny Peck <danieljpeck93@gmail.com>"]

[dependencies]
diesel = { version = "1.3.2", features = ["postgres"] }
dotenv = "0.13.0"
hyper = "0.12"
futures = "0.1"
serde = "1.0.71"
serde_json = "1.0.26"